# Generated by Django 4.2.7 on 2025-12-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('popularity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-popularity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('danceability', models.FloatField(default=0.0)),
                ('energy', models.FloatField(default=0.0)),
                ('loudness', models.FloatField(default=0.0)),
                ('valence', models.FloatField(default=0.0)),
                ('tempo', models.FloatField(default=0.0)),
                ('acousticness', models.FloatField(default=0.0)),
                ('popularity', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.artist')),
                ('genres', models.ManyToManyField(related_name='tracks', to='catalog.genre')),
            ],
            options={
                'ordering': ['-popularity'],
                'indexes': [models.Index(fields=['valence', 'energy'], name='catalog_tra_valence_0dc7bf_idx'), models.Index(fields=['popularity'], name='catalog_tra_popular_56cfb9_idx')],
            },
        ),
    ]
