# Generated by Django 4.2.7 on 2025-12-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_recommendation_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='origin_country',
            field=models.CharField(blank=True, help_text="Artist's country of origin (from MusicBrainz API)", max_length=100, null=True),
        ),
    ]
