# Generated by Django 4.2.7 on 2025-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_artist_origin_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(blank=True, help_text='Artist type: Person, Group, Orchestra, Choir, Character, Other', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, help_text='Short description from Wikidata', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='disbanded_year',
            field=models.IntegerField(blank=True, help_text='Year artist disbanded or died (from MusicBrainz)', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='enriched_at',
            field=models.DateTimeField(blank=True, help_text='When external data was last fetched', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='formed_year',
            field=models.IntegerField(blank=True, help_text='Year artist was formed or born (from MusicBrainz)', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='musicbrainz_id',
            field=models.CharField(blank=True, db_index=True, help_text='MusicBrainz artist MBID (UUID format)', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, help_text='Wikidata Q-identifier (e.g., Q1299)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['origin_country'], name='catalog_art_origin__bad30b_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['formed_year'], name='catalog_art_formed__431421_idx'),
        ),
    ]
