# Generated by Django 4.2.7 on 2025-12-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_is_audio_analyzed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='track',
            name='catalog_tra_is_audi_idx',
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['is_audio_analyzed'], name='catalog_tra_is_audi_1e9e04_idx'),
        ),
        migrations.AddField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this track was ingested into the database', null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='acousticness',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='track',
            name='danceability',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='track',
            name='energy',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='track',
            name='loudness',
            field=models.FloatField(default=-10.0),
        ),
        migrations.AlterField(
            model_name='track',
            name='tempo',
            field=models.FloatField(default=120.0),
        ),
        migrations.AlterField(
            model_name='track',
            name='valence',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['created_at'], name='catalog_tra_created_9cf92c_idx'),
        ),
    ]
