# Generated by Django 4.2.7 on 2025-12-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_track_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationfeedback',
            name='session_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
