# Generated by Django 4.2.7 on 2025-12-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_increase_session_key_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationfeedback',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
