# Generated by Django 4.2.7 on 2026-02-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_session_key_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_satisfaction', models.IntegerField(choices=[(1, 'Very Unsatisfied'), (2, 'Unsatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], help_text='Overall satisfaction with recommendations')),
                ('discovery_rating', models.IntegerField(choices=[(1, 'None - all familiar'), (2, 'A few new tracks'), (3, 'About half were new'), (4, 'Most were new to me'), (5, 'All new discoveries')], help_text='How many new tracks did you discover?')),
                ('accuracy_rating', models.IntegerField(choices=[(1, 'Not at all accurate'), (2, 'Slightly accurate'), (3, 'Moderately accurate'), (4, 'Very accurate'), (5, 'Extremely accurate')], help_text='How accurate were the recommendations to your taste?')),
                ('liked_most', models.TextField(blank=True, help_text='What did you like most about the recommendations?', null=True)),
                ('improvement_suggestion', models.TextField(blank=True, help_text='What could be improved?', null=True)),
                ('would_recommend', models.BooleanField(default=True, help_text='Would you recommend this tool to others?')),
                ('session_key', models.TextField(blank=True, null=True)),
                ('tracks_interacted', models.IntegerField(default=0, help_text='Number of tracks user interacted with before survey')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Survey',
                'verbose_name_plural': 'User Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('search', 'Search Performed'), ('recommend', 'Recommendations Generated'), ('play', 'Track Played'), ('like', 'Track Liked'), ('dislike', 'Track Disliked'), ('add_playlist', 'Added to Playlist'), ('filter_applied', 'Filter Applied'), ('survey_completed', 'Survey Completed')], db_index=True, max_length=50)),
                ('session_key', models.TextField(blank=True, db_index=True, null=True)),
                ('track_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional event data (e.g., search query, filter type)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='catalog_ana_event_t_ae08b6_idx')],
            },
        ),
    ]
