# Generated by Django 3.2.18 on 2026-02-13 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_user_survey_and_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPlaylist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_ids', models.JSONField(help_text='List of track IDs in the playlist')),
                ('preferences', models.JSONField(blank=True, help_text='Optional preference settings', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expire after this date', null=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Extra event data (search query, filter, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(blank=True, help_text='E.g. Person, Group, Orchestra', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='disbanded_year',
            field=models.IntegerField(blank=True, help_text='Year disbanded or died', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='enriched_at',
            field=models.DateTimeField(blank=True, help_text='Last enrichment timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='formed_year',
            field=models.IntegerField(blank=True, help_text='Year formed or born', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='musicbrainz_id',
            field=models.CharField(blank=True, db_index=True, help_text='MusicBrainz MBID', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='origin_country',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, help_text='Wikidata Q-identifier', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationfeedback',
            name='score',
            field=models.BooleanField(help_text='True=like, False=dislike'),
        ),
        migrations.AlterField(
            model_name='track',
            name='acousticness',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this track was added', null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='danceability',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='energy',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_audio_analyzed',
            field=models.BooleanField(default=True, help_text='False if using default values'),
        ),
        migrations.AlterField(
            model_name='track',
            name='tempo',
            field=models.FloatField(default=120.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='valence',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='accuracy_rating',
            field=models.IntegerField(choices=[(1, 'Not at all accurate'), (2, 'Slightly accurate'), (3, 'Moderately accurate'), (4, 'Very accurate'), (5, 'Extremely accurate')], help_text='Recommendation accuracy rating'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='discovery_rating',
            field=models.IntegerField(choices=[(1, 'None - all familiar'), (2, 'A few new tracks'), (3, 'About half were new'), (4, 'Most were new to me'), (5, 'All new discoveries')], help_text='How many new tracks discovered'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='improvement_suggestion',
            field=models.TextField(blank=True, help_text='Suggested improvements', null=True),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='liked_most',
            field=models.TextField(blank=True, help_text='What the user liked most', null=True),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='overall_satisfaction',
            field=models.IntegerField(choices=[(1, 'Very Unsatisfied'), (2, 'Unsatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], help_text='Overall satisfaction rating'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='tracks_interacted',
            field=models.IntegerField(default=0, help_text='Tracks interacted with before survey'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='would_recommend',
            field=models.BooleanField(default=True, help_text='Would recommend to others'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('album_type', models.CharField(blank=True, help_text='single, album, or compilation', max_length=50, null=True)),
                ('spotify_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('total_tracks', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
