# Generated by Django 3.2.18 on 2026-02-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_shared_playlist_and_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release_year',
            field=models.IntegerField(blank=True, help_text='Release year from Spotify album data', null=True),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['release_year'], name='catalog_tra_release_29a58c_idx'),
        ),
    ]
